### ISSUE TITLE
Cannot configure after install

### ISSUE THREAD

**Issue by fake-name** [bisguzar/st3-micropython-tools#1]
Step 1: Install package.
Step 2: Try opening settings.

![image](https://user-images.githubusercontent.com/1401239/43672508-36d5500e-9764-11e8-8648-4503237b81ae.png)

For manual install, the package generally goes to `st3-micropython-tools`, but the interface is trying to access `micropython`. Renaming the package directory to `micropython` does indeed fix the issue.

This occurs with both manual installation, and installation from PackageControl.

**Comment by bisguzar** [comment]
Thanks for attention, I just modified path and working well.
