### ISSUE TITLE
Error:  Failed to access  /dev/ttyUSB0. Please cgeck connection or settings.

### ISSUE THREAD

**Issue by srihariash999** [bisguzar/st3-micropython-tools#2]
I installed micropython tools using the package manager and it looks like it got installed properly. 

I can see the micropython-tools options, like settings,get, put etc;

When i try to put the file through to the microcontroller (Nodemcu v1.0) I get this error.

![Screenshot from 2019-06-09 23-55-46](https://user-images.githubusercontent.com/30948010/59162665-9ced9980-8b12-11e9-8b3f-a594447fe140.png)

**Comment by bisguzar** [comment]
You need to define location of board which one running microPython. It's trying to upload to /dev/ttyUSB0 because the default port is it. 
You can change it from settings. Just open command palette (CTRL+Shift+P) and type "MicroPython: Settings". Than configure preferences and save the file.
